export const STRINGS = {
  card: {
    connectionLost: 'Connection lost',
    reconnected: 'Reconnected',
    actionFailed: 'Action failed — please retry',
    loading: 'Loading...',
    invalidConfigurationTitle: 'flowme: invalid configuration',
    noConnection: 'no connection',
    entityNotFound: 'entity not found',
    error: 'Error',
    hacsDescription: 'Animated flow visualisation over a custom background image',
  },
  security: {
    unsafeUrlInCard: (scheme: string, path: string) =>
      `Unsafe URL scheme '${scheme}' in ${path}. flowme rejects javascript:, vbscript:, data: and file: URLs inside custom overlay configs.`,
  },
  overlays: {
    haHelpersUnavailable: 'HA card helpers unavailable',
    migrationPrefix: '⚠',
  },
  editor: {
    hintNoConfig: 'No configuration loaded yet. Use "Show code editor" to paste YAML.',
    canvas: {
      ariaLabel: 'FlowMe visual editor canvas',
      addNodeAria: 'Add node — then click canvas to place',
      addFlowAria: 'Add flow between two nodes',
      addOverlayAria: 'Add overlay card',
      saveAria: 'Save configuration to Home Assistant',
      saveTitle: 'Apply current configuration to the card',
      cancelAria: 'Discard editor changes',
      cancelTitle: 'Discard all changes since the editor opened',
      selectTypeAria: 'Select element type',
      selectElementAria: 'Select element',
      undoTitleWithDesc: (desc: string) => `Undo: ${desc} (Ctrl+Z)`,
      undoTitlePlain: 'Undo (Ctrl+Z)',
      redoTitleWithDesc: (desc: string) => `Redo: ${desc} (Ctrl+Shift+Z)`,
      redoTitlePlain: 'Redo (Ctrl+Shift+Z)',
      overlayOption: (index: number, idPart: string) => `Overlay ${index + 1}${idPart}`,
      overlayOptionIdPart: (id: string) => ` (${id})`,
    },
    toolbar: {
      undo: 'Undo',
      redo: 'Redo',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      fitCanvas: 'Fit to canvas',
      addNode: '+ Node',
      addFlow: '+ Flow',
      addOverlay: '+ Overlay',
      save: 'Save',
      cancel: 'Cancel',
      suggestPath: 'Suggest path',
      suggestPathFinding: 'Finding path…',
      hide: 'Hide',
      acceptPath: 'Accept suggested path',
      cancelPath: 'Cancel suggested path',
      alignHorizontal: 'Align horizontal',
      alignVertical: 'Align vertical',
      alignHorizontalShort: 'Align H',
      alignVerticalShort: 'Align V',
      showSelected: 'Show',
      hideSelected: 'Hide',
      deleteSelected: 'Delete',
      hideSelectedNodesAria: 'Hide selected nodes',
      showSelectedNodesAria: 'Show selected nodes',
      alignSelectedHorizontalAria: 'Align selected nodes horizontally',
      alignSelectedVerticalAria: 'Align selected nodes vertically',
      deleteSelectedNodesAria: 'Delete selected nodes',
      clearMultiSelectionAria: 'Clear multi-selection',
      deselect: '✕ Deselect',
      selectType: 'Select type…',
      selectElement: 'Select element…',
      selectElementDash: '—',
      nodes: 'Nodes',
      flows: 'Flows',
      overlays: 'Overlays',
    },
    nodeEffect: {
      section: 'Node effect',
      active: 'This node has a visual effect',
      type: 'Effect type',
      none: 'None',
      glow: 'Glow',
      badge: 'Badge',
      ripple: 'Ripple',
      alert: 'Alert',
      glowColor: 'Glow colour',
      glowMaxRadius: 'Glow max radius (px)',
      glowMinIntensity: 'Minimum glow intensity',
      peakValue: 'Peak sensor value',
      badgeColorOn: 'Badge on colour',
      badgeColorOff: 'Badge off colour',
      threshold: 'Numeric threshold',
      rippleColor: 'Ripple colour',
      rippleDuration: 'Ripple cycle (ms)',
      rippleThreshold: 'Ripple min value',
      alertThreshold: 'Alert threshold',
      alertCondition: 'Condition',
      alertColor: 'Alert colour',
      alertFrequency: 'Flash frequency (Hz)',
      alertHysteresis: 'Hysteresis (fraction)',
      above: 'Above',
      below: 'Below',
      needsEntity: 'Choose an entity — node effects use live sensor state.',
    },
    standaloneToolbar: {
      addNodeTitle: 'Add node',
      addFlowTitle: 'Add flow',
      addOverlayTitle: 'Add overlay',
      suggestDisabled:
        'Shift+click exactly two nodes to suggest a path between them',
      suggestEnabled:
        'Create a new flow with auto-routed waypoints between the two selected nodes',
      undoTitleWithDesc: (desc: string) => `Undo: ${desc}`,
      undoTitlePlain: 'Undo (⌘Z)',
      redoTitleWithDesc: (desc: string) => `Redo: ${desc}`,
      redoTitlePlain: 'Redo (⌘⇧Z)',
      togglePreviewTitle: 'Toggle preview animations',
      editing: 'Editing',
      preview: 'Preview',
      keyboardHint:
        'Shift+click node = select for path · Shift+drag = snap · right-click to delete',
      saveTitle: 'Apply to card config',
    },
    inspector: {
      node: 'Node',
      flow: 'Flow',
      overlay: 'Overlay',
      label: 'Label',
      flowIdField: 'Flow id',
      overlayIdField: 'Overlay id',
      entity: 'Entity',
      colour: 'Colour',
      visible: 'Visible',
      opacity: 'Opacity',
      positionX: 'X %',
      positionY: 'Y %',
      size: 'Size',
      sizePx: 'Size px',
      showValue: 'Show value',
      showLabel: 'Show label',
      deleteNode: 'Delete node',
      deleteFlow: 'Delete flow',
      deleteOverlay: 'Delete overlay',
      lineStyle: 'Line style',
      animation: 'Animation',
      waypoints: 'Waypoints',
      waypointCount: (n: number) => String(n),
      addWaypoint: '+ Add waypoint',
      deleteWaypoint: 'Delete waypoint',
      deleteWaypointAria: (index: number) => `Delete waypoint ${index + 1}`,
      addWaypointOnFlowAria: 'Add waypoint on flow',
      speedCurve: 'Speed curve',
      speedCurveOverrideSummary: 'Speed curve override',
      resetToDefaults: 'Reset to defaults',
      resetToDomainDefaults: 'Reset to domain defaults',
      valueGradient: 'Value gradient',
      enableGradient: 'Enable value gradient',
      removeGradient: 'Remove gradient',
      fluidIgnoresParticleShape:
        'Fluid style uses a flowing gradient along the line — particle shape is ignored.',
      particleSpacing: 'Particle spacing',
      cardConfig: 'Card configuration (any HA card YAML)',
      invalidYaml: 'Invalid YAML',
      invalidCardJson: (detail: string) => `Invalid JSON: ${detail}`,
      width: 'Width %',
      height: 'Height %',
      nodeHeading: (id: string) => `Node: ${id}`,
      flowHeading: (id: string) => `Flow: ${id}`,
      overlayHeading: (id: string) => `Overlay: ${id}`,
      routeAndSensor: 'Route and sensor',
      fromNode: 'From node',
      toNode: 'To node',
      fromToSameError: 'From and To must be different nodes',
      colourOverride: 'Colour override',
      colourOverrideActive: 'override',
      colourDomainDefault: 'domain default',
      clearColour: 'Clear',
      flowOpacity: 'Flow opacity',
      shown: 'shown',
      hidden: 'hidden',
      flowVisible: 'Visible',
      speedCurveHint: (unitLabel: string, domain: string) =>
        `Leave blank to use domain profile defaults. Domain: ${unitLabel} (${domain})`,
      previewAtPoints: 'Preview (at threshold / p50 / peak):',
      threshold: 'Threshold',
      medianP50: 'Median (p50)',
      peak: 'Peak',
      maxDuration: 'Max duration',
      minDuration: 'Min duration',
      steepness: 'Steepness',
      ms: 'ms',
      k: 'k',
      style: 'Style',
      particleShape: 'Particle shape',
      svgPathLabel: 'SVG path (d= attribute)',
      svgPathPlaceholder: 'M 0 -8 L 5 8 L -5 8 Z',
      direction: 'Direction',
      particleSize: 'Particle size',
      particleCount: 'Particle count',
      profileDefaultPlaceholder: 'profile default',
      glowIntensity: 'Glow intensity',
      shimmerThreshold: 'Shimmer at threshold',
      flicker: 'Flicker (random opacity variation)',
      trailLength: 'Trail length',
      dashGapRatio: 'Dash gap ratio',
      clusterSize: 'Cluster size',
      clusterGap: 'Cluster gap (×)',
      pulseFrequencyHz: 'Pulse frequency (Hz)',
      pulseRatio: 'Pulse ratio',
      waveFrequency: 'Wave frequency',
      waveAmplitudePx: 'Wave amplitude (px)',
      waveAmplitude01: 'Wave amplitude (0–1)',
      gradientEntity: 'Gradient entity',
      gradientEntityPlaceholder: 'sensor.my_temperature',
      lowValue: 'Low value',
      highValue: 'High value',
      lowColour: 'Low colour',
      highColour: 'High colour',
      applyGradientTo: 'Apply gradient to',
      gradientModeFlow: 'Particles only',
      gradientModeLine: 'Line only',
      gradientModeBoth: 'Particles and line',
      waypointEmpty:
        'No waypoints — click on the flow line to add one.',
      waypointSectionHash: '#',
      waypointCoordX: 'x%',
      waypointCoordY: 'y%',
      animationGlobalSummary: 'Animation (global)',
      fpsCap: 'FPS cap',
      fpsSuffix: 'fps',
      smoothSpeedHint:
        'Smooth speed: interpolates duration changes over 500ms instead of restarting abruptly.',
      on: 'on',
      off: 'off',
      applyCardConfig: 'Apply card config',
      cardConfigPlaceholder: 'type: entity\nentity: sensor.my_sensor',
      cardConfigHintExamples:
        'Any installed HA card type is supported. Examples: entity, tile, gauge, picture-entity, custom:mini-graph-card, …',
      cardConfigHintUrls:
        'URLs must not use javascript:, vbscript:, data: or file: schemes.',
      opacitySummary: 'Opacity',
      opacityHint:
        'Adjust opacity for each visual layer. 1.0 = fully opaque, 0.0 = invisible. "Darken" is 0 by default (no darkening overlay).',
      opacityBackground: 'Background image',
      opacityDarken: 'Background darkening (0=none, 1=black)',
      opacityNodes: 'Nodes',
      opacityFlows: 'Flow lines',
      opacityDots: 'Animated dots',
      opacityGlow: 'Glow effect',
      opacityLabels: 'Labels',
      opacityValues: 'Values',
      opacityOverlays: 'Overlays (all)',
      domainColoursSummary: 'Domain colours',
      domainColoursHint:
        'Override default colours for each role in the selected domain. Changes apply to all flows unless a per-flow colour is set.',
      colourDefaultSuffix: (hex: string) => `${hex} (default)`,
      reset: 'Reset',
      visibilitySummary: 'Visibility',
      visibilityHint:
        'Binary show/hide for each rendering layer. Independent of opacity.',
      visibilityFlowLines: 'Flow lines',
      visibilityAnimatedDots: 'Animated dots',
      visibilityVisible: 'visible',
      visibilityHidden: 'hidden',
      defaultsSummary: 'Defaults',
      defaultsHint:
        'Card-level rendering defaults. All fields are optional — omitting them keeps the built-in values shown in parentheses.',
      burstTriggerRatio: 'Burst trigger ratio (0–1)',
      burstSustainMs: 'Burst sustain (ms)',
      burstMaxParticles: 'Burst max particles',
      multiselectCount: (n: number) => `${n} nodes selected`,
      suggestPathBetweenAria: 'Suggest path between two selected nodes',
      suggestPathBetweenTitle: 'Suggest path between selected nodes',
      suggestPathPickTwoTitle: 'Select exactly 2 nodes to suggest a path',
      deleteNodesConfirm: (n: number) =>
        `Delete ${n} nodes (and their flows)?`,
      deleteOverlayConfirm: (id: string) => `Delete overlay ${id}?`,
      deleteNodeContextConfirm: (id: string) =>
        `Delete node ${id}? This also removes any flows using it.`,
      weatherPanelSummary: 'Backgrounds & weather',
      defaultImageUrl: 'Default image URL',
      defaultBgPlaceholder: '/local/flowme/house.jpg',
      defaultBgAlt: 'default background',
      weatherEntityOptional: 'Weather entity (optional)',
      weatherPlaceholder: 'weather.forecast_home',
      currentState: 'Current state:',
      weatherMatched: 'matched',
      weatherNoMapping: 'no mapping (using default)',
      sunEntityOptional:
        'Sun entity (optional) — enables automatic night background variants',
      sunPlaceholder: 'sun.sun',
      sunAbove: '☀️ above horizon',
      sunBelow: '🌙 below horizon',
      sunStateLabel: 'Sun:',
      fadeTransitionSeconds: 'Fade transition (seconds)',
      weatherStateColumn: 'State',
      weatherImageUrlColumn: 'Image URL',
      weatherRowPlaceholder: '/local/flowme/rainy.jpg',
      remove: 'Remove',
      addWeatherState: '+ Add weather state',
      metNoReferenceSummary: 'Standard Met.no state list (for reference)',
      metNoHint:
        'Any state string is accepted — custom integrations can use any key. State strings are matched exactly as Home Assistant provides them (lowercase, hyphenated).',
      suggestCorsError:
        'Could not analyse the background image (likely a CORS issue). Serve it from the same origin as Home Assistant and try again.',
      suggestAutoRouteFailed: (msg: string) => `Auto-route failed: ${msg}`,
      flowEntityPrompt: 'Entity for this flow (e.g. sensor.grid_power):',
      flowEntityDefault: 'sensor.placeholder_entity',
      suggestPreviewWaypoints: (n: number) =>
        `Preview — ${n} waypoint(s)`,
      accept: 'Accept',
      newNodeDefaultLabel: 'New node',
      entityPickerFallbackPlaceholder: 'entity.id',
      showNode: 'Show node',
      hideNode: 'Hide node',
    },
    stateA: {
      domainSummary: 'Diagram domain',
      domain: 'Domain',
      domainOption: {
        energy: 'Energy',
        water: 'Water',
        network: 'Network',
        hvac: 'HVAC',
        gas: 'Gas',
        generic: 'Generic',
      },
      background: 'Background',
      appearance: 'Appearance',
      defaults: 'Defaults',
      backgroundImage: 'Background image URL',
      weatherEntity: 'Weather entity',
      sunEntity: 'Sun entity (optional)',
      transitionDuration: 'Transition duration (seconds)',
      addWeatherMapping: 'Add mapping',
      weatherState: 'Weather state',
      imageUrl: 'Image URL',
      domainColours: 'Domain colours',
      solar: 'Solar',
      grid: 'Grid',
      battery: 'Battery',
      load: 'Load',
      nodeRadius: 'Node radius (px)',
      dotRadius: 'Dot radius (px)',
      lineWidth: 'Line width (px)',
      fps: 'FPS cap',
      smoothSpeed: 'Smooth speed transitions',
    },
    suggestBar: {
      message: 'Suggested path ready — accept or cancel',
    },
    domainRoles: {
      energy: {
        solar: 'Solar',
        grid: 'Grid',
        battery: 'Battery',
        load: 'Load',
      },
      water: {
        supply: 'Supply',
        drain: 'Drain',
        storage: 'Storage',
        transfer: 'Transfer',
      },
      network: {
        upload: 'Upload',
        download: 'Download',
        local: 'Local',
        external: 'External',
      },
      hvac: {
        supply: 'Supply air',
        return: 'Return air',
        fresh: 'Fresh air',
        exhaust: 'Exhaust',
      },
      gas: {
        inlet: 'Inlet',
        outlet: 'Outlet',
        bypass: 'Bypass',
        vent: 'Vent',
      },
      generic: {
        flow1: 'Flow 1',
        flow2: 'Flow 2',
        flow3: 'Flow 3',
        flow4: 'Flow 4',
      },
    },
    errors: {
      invalidCardConfig: 'Invalid card config',
      noFlowSelected: 'Select a flow to edit',
      noNodeSelected: 'Select a node to edit',
      renameIdConflict: 'That id is already in use — choose a unique id.',
    },
  },
  aria: {
    card: 'FlowMe energy flow visualisation',
    nodeHandle: (label: string, x: number, y: number) =>
      `Node ${label} at ${x.toFixed(1)}%, ${y.toFixed(1)}%`,
    waypointHandle: (index: number, flowLabel: string) =>
      `Waypoint ${index + 1} of flow ${flowLabel}`,
    flowGroup: (label: string, value: string) => `${label}: ${value}`,
    overlayHandle: (id: string) => `Overlay ${id}`,
    readingWithTitle: (title: string, reading: string) => `${title}: ${reading}`,
  },
  validation: {
    configMustBeObject: 'config must be an object',
    mustBeObjectWithXY: 'must be an object with x and y',
    mustBeFiniteNumber: 'must be a finite number',
    percentRange: (v: number) => `must be in range 0-100, got ${v}`,
    mustBeNonEmptyString: 'must be a non-empty string',
    urlMustStartWith: (prefixes: string, preview: string) =>
      `must start with one of ${prefixes} (got "${preview}")`,
    mustBeObject: 'must be an object',
    mustBeNonEmptyId: 'must be a non-empty string',
    duplicateNodeId: (id: string) => `duplicate node id "${id}"`,
    duplicateFlowId: (id: string) => `duplicate flow id "${id}"`,
    unknownNodeRef: (id: string) => `references unknown node "${id}"`,
    mustBeNonEmptyEntityId: 'must be a non-empty entity id',
    waypointsMustBeArray: 'must be an array (may be empty or omitted)',
    mustBeOneOf: (list: string) => `must be one of ${list}`,
    speedMultiplierRange: 'must be between 0.1 and 5.0',
    mustBeBoolean: 'must be a boolean',
    mustBeString: 'must be a string',
    invalidNodeEffectType: 'node_effect.type must be glow, badge, ripple, or alert',
    positiveFinite: 'must be a positive finite number',
    durationMin50: 'must be a finite number ≥ 50 (milliseconds)',
    minLtMaxDuration: 'min_duration must be < max_duration',
    unknownKey: (allowed: string) => `unknown key (allowed: ${allowed})`,
    defaultsMustBeObject: 'must be an object',
    burstTriggerMax1: 'must be ≤ 1 (it is a fraction of peak)',
    opacity01: 'must be a number between 0 and 1',
    opacityRootMustBeObject: 'must be an object',
    mustBeSvgPathString: 'must be a string (SVG path d= attribute)',
    mustBeAtMost: (max: number) => `must be ≤ ${max}`,
    particleCountInt: 'must be a positive integer ≥ 1',
    glowNonNegative: 'must be a non-negative finite number',
    dashGapRange: 'must be a number between 0 and 10',
    pulseRatioRange:
      'must be a number between 0 (exclusive) and 1 (exclusive)',
    mustBeHexColor:
      'must be a CSS hex colour string, e.g. "#FF4500" or "#f00"',
    mustBeStringEntityId: 'must be a string entity id',
    finiteNumber: 'must be a finite number',
    gradientMode: 'must be one of: flow, line, both',
    animationRootMustBeObject: 'must be an object',
    fpsRange: 'must be a number between 1 and 120',
    visibilityRootMustBeObject: 'must be an object',
    domainColorsRootMustBeObject: 'must be an object',
    stringColourValue: 'must be a string colour value',
    typeMustBeFlowme: (got: string) =>
      `must equal "custom:flowme-card" (got "${got}")`,
    backgroundWhenProvided: 'must be an object when provided',
    weatherStatesMapping:
      'must be an object mapping state strings to image URLs',
    sunEntityExample: 'must be a string entity id (e.g. sun.sun)',
    transitionMustBeNumberMs: 'must be a number (milliseconds)',
    nodesMustBeArray: 'must be an array',
    atLeastOneNode: 'at least one node is required',
    flowsMustBeArray: 'must be an array',
    aspectRatioRegex: 'must match regex \\d+:\\d+ (e.g. "16:10")',
    editPasswordMustBeString: 'must be a string',
    overlaysMustBeArray: 'must be an array',
    overlayTypeMustBeCustom:
      'must be "custom" — native overlay types (camera, switch, sensor, button) were removed in v1.0.9. Use type: custom with a card: block instead.',
    duplicateOverlayId: (id: string) => `duplicate overlay id "${id}"`,
    overlayCardMustBeObject:
      'must be a HA card config object (e.g. { type: "entity", entity: "sensor.my_sensor" })',
    unsafeSchemeInCard: (scheme: string) =>
      `unsafe URL scheme "${scheme}" — flowme rejects javascript:, vbscript:, data: and file: URLs in overlay card configs`,
    overlaySizeMustBeObject: 'must be an object with width and height',
    overlayWidthPercent: 'must be a positive number ≤ 100 (percent of card)',
    overlayHeightPercent: 'must be a positive number ≤ 100 (percent of card)',
    overlayOpacity01: 'must be a number between 0 and 1',
    migrationOverlayWarning: (type: string) =>
      `type: ${type} was removed in v1.0.9. Replace with type: custom and a card: block. See documentation.`,
  },
} as const;

export type StringKey = typeof STRINGS;
